<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>popUp email atau kata sandi salah</name>
   <tag></tag>
   <elementGuidId>bdaa39b9-ba20-4dc4-9ab9-aaec32c58772</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.Toast</value>
      <webElementGuid>8b5c5b52-8ea5-4a3c-bde5-20fe607112d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>12ed85dc-c1bf-4bbd-bade-e738c79a7772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email atau kata sandi salah</value>
      <webElementGuid>98124082-b7cd-4c97-a0ef-5c4467060c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.android.settings</value>
      <webElementGuid>a931fbda-f91b-45ff-8a40-697460259d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5668fc95-45b1-4e9e-9b6c-8a4d36908863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.Toast[1]</value>
      <webElementGuid>cf7142a7-5ec3-43ef-8e24-07a98b11c775</webElementGuid>
   </webElementProperties>
   <locator>//hierarchy/android.widget.Toast[1]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
